/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.ApcVendedor;
import dao.DAO_ApcVendedor;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author u09947038130
 */
public class JDlgApc_Vendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuarios
     */
    boolean alterar = false;
    boolean foiPesquisado = false;
    
    public JDlgApc_Vendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jFmtApc_Cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String cpf = jFmtApc_Cpf.getText();
                if (!Util.isValidCPF(cpf)) {
                    JOptionPane.showMessageDialog(null, "O CPF preenchido é inválido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                    jFmtApc_Cpf.setText("");
                    jFmtApc_Cpf.requestFocus();
                }
            }
        });
        setTitle("Cadastro de Vendedores");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);

    }
    
    public ApcVendedor viewBean() {
        ApcVendedor vendedor = new ApcVendedor();
        vendedor.setApcIdVendedor(Util.strToInt(jTxtApc_Codigo.getText()));
        vendedor.setApcNome(jTxtApc_Nome.getText());
        vendedor.setApcCpf(jFmtApc_Cpf.getText());
        vendedor.setApcDataNascimento(Util.strToDate(jFmtApc_DataNascimento.getText()));

        if (jCboApc_Sexo.getSelectedItem().toString().equals("Masculino")) {
            vendedor.setApcSexo("M");
        } else {
            vendedor.setApcSexo("F");
        }

        vendedor.setApcTelefoneResidencial(jFmtApc_TelefoneResidencial.getText());
        vendedor.setApcCelular(jFmtApc_Celular.getText());
        vendedor.setApcCep(jFmtApc_Cep.getText());
        vendedor.setApcEndereco(jTxtApc_Endereco.getText());
        vendedor.setApcBairro(jTxtApc_Bairro.getText());
        vendedor.setApcCidade(jTxtApc_Cidade.getText());
        vendedor.setApcCargo(jCboApc_Cargo.getSelectedIndex());
        vendedor.setApcSalario(Util.strToDouble(jTxtApc_Salario.getText()));
        vendedor.setApcDataAdimissao(Util.strToDate(jFmtApc_DataAdmissao.getText()));

        vendedor.setApcAtivo(jChbApc_Ativo.isSelected() ? "S" : "N");

        return vendedor;
    }

    public void beanView(ApcVendedor vendedor) {
        jTxtApc_Codigo.setText(Util.intToStr(vendedor.getApcIdVendedor()));
        jTxtApc_Nome.setText(vendedor.getApcNome());
        jFmtApc_Cpf.setText(vendedor.getApcCpf());
        jFmtApc_DataNascimento.setText(Util.dateToStr(vendedor.getApcDataNascimento()));
        if (vendedor.getApcSexo().equals("M")) {
            jCboApc_Sexo.setSelectedItem("Masculino");
        } else {
            jCboApc_Sexo.setSelectedItem("Feminino");
        }
        jFmtApc_TelefoneResidencial.setText(vendedor.getApcTelefoneResidencial());
        jFmtApc_Celular.setText(vendedor.getApcCelular());
        jFmtApc_Cep.setText(vendedor.getApcCep());
        jTxtApc_Endereco.setText(vendedor.getApcEndereco());
        jTxtApc_Bairro.setText(vendedor.getApcBairro());
        jTxtApc_Cidade.setText(vendedor.getApcCidade());
        jCboApc_Cargo.setSelectedIndex((vendedor.getApcCargo()));
        jTxtApc_Salario.setText(Util.doubleToStr(vendedor.getApcSalario()));
        jFmtApc_DataAdmissao.setText(Util.dateToStr(vendedor.getApcDataAdimissao()));
        jChbApc_Ativo.setSelected(vendedor.getApcAtivo().equals("S"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLblCodigo = new javax.swing.JLabel();
        jTxtApc_Codigo = new javax.swing.JTextField();
        jLblCodigo1 = new javax.swing.JLabel();
        jTxtApc_Nome = new javax.swing.JTextField();
        jFmtApc_DataNascimento = new javax.swing.JFormattedTextField();
        jChbApc_Ativo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFmtApc_Cpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jCboApc_Sexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jFmtApc_TelefoneResidencial = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmtApc_Celular = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFmtApc_Cep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtApc_Endereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtApc_Bairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtApc_Cidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFmtApc_DataAdmissao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jCboApc_Cargo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTxtApc_Salario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apagar.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLblCodigo.setText("Código");

        jLblCodigo1.setText("Nome");

        try {
            jFmtApc_DataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtApc_DataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtApc_DataNascimentoActionPerformed(evt);
            }
        });

        jChbApc_Ativo.setText("Ativo");
        jChbApc_Ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbApc_AtivoActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        jLabel2.setText("Data de Nascimento");

        try {
            jFmtApc_Cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtApc_Cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtApc_CpfActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo");

        jCboApc_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Masculino", "Feminino" }));
        jCboApc_Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboApc_SexoActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefone Residencial");

        try {
            jFmtApc_TelefoneResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Celular");

        try {
            jFmtApc_Celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("CEP");

        try {
            jFmtApc_Cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Endereço");

        jLabel10.setText("Bairro");

        jLabel11.setText("Cidade");

        jLabel12.setText("Data de Admissão");

        try {
            jFmtApc_DataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Cargo/Função");

        jCboApc_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Administrador", "Gerente", "Vendedor", "Gerenciador de Estoque" }));

        jLabel13.setText("Salário");

        jTxtApc_Salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApc_SalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtApc_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtApc_Nome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCodigo)
                                .addGap(69, 69, 69)
                                .addComponent(jLblCodigo1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisar)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFmtApc_Cpf)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFmtApc_TelefoneResidencial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtApc_Endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboApc_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFmtApc_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCboApc_Sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtApc_Bairro)
                                        .addComponent(jFmtApc_Celular, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtApc_Cep)
                                    .addComponent(jTxtApc_Cidade)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtApc_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFmtApc_DataAdmissao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbApc_Ativo)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo)
                    .addComponent(jLblCodigo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApc_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtApc_Cpf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCboApc_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtApc_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtApc_TelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtApc_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtApc_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApc_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApc_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApc_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboApc_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtApc_DataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbApc_Ativo)
                    .addComponent(jTxtApc_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (!foiPesquisado) {
            Util.mensagem("Você deve pesquisar primeiro!");
            return;
        } else {
            alterar = true;
            Util.habilitar(true, jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, 
                jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, 
                jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, 
                jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, 
                jBtnConfirmar, jBtnCancelar);

            Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        }
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jFmtApc_CpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtApc_CpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtApc_CpfActionPerformed

    private void jChbApc_AtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbApc_AtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbApc_AtivoActionPerformed

    private void jFmtApc_DataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtApc_DataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtApc_DataNascimentoActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.limpar(jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);
        jTxtApc_Codigo.grabFocus();
        alterar = false;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (!foiPesquisado) {
            Util.mensagem("Você deve pesquisar primeiro!");
            return;
        } else {
            if (Util.perguntar("Deseja realmente Excluir?") == true) {
                DAO_ApcVendedor vendedorDAO = new DAO_ApcVendedor();
                vendedorDAO.delete(viewBean());
            }
        }
        Util.limpar(jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        DAO_ApcVendedor dao_ApcVendedor = new DAO_ApcVendedor();
        
        if (alterar == false){
            dao_ApcVendedor.insert(viewBean());
        } else{
            dao_ApcVendedor.update(viewBean());
        }
        Util.limpar(jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.limpar(jTxtApc_Nome, jTxtApc_Salario, jTxtApc_Endereco, jTxtApc_Codigo, jTxtApc_Cidade, jTxtApc_Bairro, jFmtApc_Celular, jFmtApc_Cep, jFmtApc_Cpf, jFmtApc_DataAdmissao, jFmtApc_DataNascimento, jFmtApc_DataNascimento, jFmtApc_TelefoneResidencial, jCboApc_Sexo, jChbApc_Ativo, jCboApc_Cargo, jBtnConfirmar, jBtnCancelar);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgApc_VendedorPesquisar jDlgApc_VendedorPesquisar = new JDlgApc_VendedorPesquisar(null, true);
        jDlgApc_VendedorPesquisar.setTelaPai(this);
        jDlgApc_VendedorPesquisar.setVisible(true);
        foiPesquisado = true;
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jCboApc_SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboApc_SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboApc_SexoActionPerformed

    private void jTxtApc_SalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApc_SalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApc_SalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgApc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgApc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgApc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgApc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgApc_Vendedor dialog = new JDlgApc_Vendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboApc_Cargo;
    private javax.swing.JComboBox<String> jCboApc_Sexo;
    private javax.swing.JCheckBox jChbApc_Ativo;
    private javax.swing.JFormattedTextField jFmtApc_Celular;
    private javax.swing.JFormattedTextField jFmtApc_Cep;
    private javax.swing.JFormattedTextField jFmtApc_Cpf;
    private javax.swing.JFormattedTextField jFmtApc_DataAdmissao;
    private javax.swing.JFormattedTextField jFmtApc_DataNascimento;
    private javax.swing.JFormattedTextField jFmtApc_TelefoneResidencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblCodigo1;
    private javax.swing.JTextField jTxtApc_Bairro;
    private javax.swing.JTextField jTxtApc_Cidade;
    private javax.swing.JTextField jTxtApc_Codigo;
    private javax.swing.JTextField jTxtApc_Endereco;
    private javax.swing.JTextField jTxtApc_Nome;
    private javax.swing.JTextField jTxtApc_Salario;
    // End of variables declaration//GEN-END:variables
}
