/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u09947038130
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Sistema de Vendas de Acessórios para Computador");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnClientesTB = new javax.swing.JButton();
        jBtnProdutosTB = new javax.swing.JButton();
        jBtnVendasTB = new javax.swing.JButton();
        jBtnConsultaProdutosTB = new javax.swing.JButton();
        jBtnConsultaVendasTB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuVendedor = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuConsultas = new javax.swing.JMenu();
        jMnuConsultaVendas = new javax.swing.JMenuItem();
        jMnuConsultaProdutos = new javax.swing.JMenuItem();
        jMnuConsultaVendedores = new javax.swing.JMenuItem();
        jMnuConsultaClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBtnClientesTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jBtnClientesTB.setFocusable(false);
        jBtnClientesTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClientesTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClientesTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesTBActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClientesTB);

        jBtnProdutosTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jBtnProdutosTB.setFocusable(false);
        jBtnProdutosTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProdutosTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProdutosTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutosTBActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnProdutosTB);

        jBtnVendasTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jBtnVendasTB.setFocusable(false);
        jBtnVendasTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendasTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendasTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasTBActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendasTB);

        jBtnConsultaProdutosTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultaProdutos.png"))); // NOI18N
        jBtnConsultaProdutosTB.setFocusable(false);
        jBtnConsultaProdutosTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultaProdutosTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultaProdutosTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultaProdutosTBActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultaProdutosTB);

        jBtnConsultaVendasTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultaVendas.png"))); // NOI18N
        jBtnConsultaVendasTB.setFocusable(false);
        jBtnConsultaVendasTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultaVendasTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultaVendasTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultaVendasTBActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultaVendasTB);

        jMnuCadastros.setText("Cadastros");
        jMnuCadastros.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMnuCadastrosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuClientes);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuUsuarios);

        jMnuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png"))); // NOI18N
        jMnuVendedor.setText("Funcionário & Vendedor");
        jMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuVendedor);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuProdutos);
        jMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuSair);

        jMenuBar1.add(jMnuCadastros);

        jMnuMovimento.setText("Movimento");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas);

        jMenuBar1.add(jMnuMovimento);

        jMnuConsultas.setText("Consultas");

        jMnuConsultaVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultaVendas.png"))); // NOI18N
        jMnuConsultaVendas.setText("Vendas");
        jMnuConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendasActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuConsultaVendas);

        jMnuConsultaProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultaProdutos.png"))); // NOI18N
        jMnuConsultaProdutos.setText("Produtos");
        jMnuConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaProdutosActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuConsultaProdutos);

        jMnuConsultaVendedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png"))); // NOI18N
        jMnuConsultaVendedores.setText("Vendedores");
        jMnuConsultaVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendedoresActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuConsultaVendedores);

        jMnuConsultaClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuConsultaClientes.setText("Clientes");
        jMnuConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaClientesActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuConsultaClientes);

        jMenuBar1.add(jMnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuCadastrosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMnuCadastrosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuCadastrosAncestorAdded

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        JDlgApc_Clientes jDlgClientes = new JDlgApc_Clientes(this, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgApc_Usuarios jDlgUsuarios = new JDlgApc_Usuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorActionPerformed
        // TODO add your handling code here:
        JDlgApc_Vendedor jDlgVendedor = new JDlgApc_Vendedor(this, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        JDlgApc_Produtos jDlgProdutos = new JDlgApc_Produtos(this, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
        JDlgApc_Vendas jDlgVendas = new JDlgApc_Vendas(this, true);
        jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jBtnClientesTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesTBActionPerformed
        // TODO add your handling code here:
        jMnuClientesActionPerformed(null);
    }//GEN-LAST:event_jBtnClientesTBActionPerformed

    private void jBtnConsultaProdutosTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultaProdutosTBActionPerformed
        // TODO add your handling code here:
        jMnuConsultaProdutosActionPerformed(null);
    }//GEN-LAST:event_jBtnConsultaProdutosTBActionPerformed

    private void jBtnConsultaVendasTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultaVendasTBActionPerformed
        // TODO add your handling code here:
        jMnuConsultaVendasActionPerformed(null);
    }//GEN-LAST:event_jBtnConsultaVendasTBActionPerformed

    private void jMnuConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendasActionPerformed
        // TODO add your handling code here:
        JDlgApc_ConsultaVendas jDlgApc_ConsultaVendas = new JDlgApc_ConsultaVendas(this, true);
        jDlgApc_ConsultaVendas.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendasActionPerformed

    private void jMnuConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaProdutosActionPerformed
        // TODO add your handling code here:
        JDlgApc_ConsultaProdutos jDlgApc_ConsultaProdutos = new JDlgApc_ConsultaProdutos(this, true);
        jDlgApc_ConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaProdutosActionPerformed

    private void jMnuConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaClientesActionPerformed
        // TODO add your handling code here:
        JDlgApc_ConsultaClientes jDlgApc_ConsultaClientes = new JDlgApc_ConsultaClientes(this, true);
        jDlgApc_ConsultaClientes.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaClientesActionPerformed

    private void jMnuConsultaVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendedoresActionPerformed
        // TODO add your handling code here:
        JDlgApc_ConsultaVendedor jDlgApc_ConsultaVendedor = new JDlgApc_ConsultaVendedor(this, true);;;
        jDlgApc_ConsultaVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendedoresActionPerformed

    private void jBtnVendasTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasTBActionPerformed
        // TODO add your handling code here:
        jMnuVendasActionPerformed(null);
    }//GEN-LAST:event_jBtnVendasTBActionPerformed

    private void jBtnProdutosTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutosTBActionPerformed
        // TODO add your handling code here:
        jMnuProdutosActionPerformed(null);
    }//GEN-LAST:event_jBtnProdutosTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            JDlgApc_Login login = new JDlgApc_Login(null, true); // true = modal
            login.setVisible(true);            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClientesTB;
    private javax.swing.JButton jBtnConsultaProdutosTB;
    private javax.swing.JButton jBtnConsultaVendasTB;
    private javax.swing.JButton jBtnProdutosTB;
    private javax.swing.JButton jBtnVendasTB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuConsultaClientes;
    private javax.swing.JMenuItem jMnuConsultaProdutos;
    private javax.swing.JMenuItem jMnuConsultaVendas;
    private javax.swing.JMenuItem jMnuConsultaVendedores;
    private javax.swing.JMenu jMnuConsultas;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
