package bean;
// Generated 07/10/2025 13:47:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApcClientes generated by hbm2java
 */
@Entity
@Table(name="apc_clientes"
    ,catalog="db_arthur_conceicao"
)
public class ApcClientes  implements java.io.Serializable {


     private int apcIdClientes;
     private String apcNome;
     private String apcCpf;
     private String apcRg;
     private String apcSexo;
     private Date apcDataNascimento;
     private String apcEmail;
     private String apcCep;
     private String apcEndereco;
     private String apcBairro;
     private String apcCidade;
     private String apcTelefoneResidencial;
     private String apcCelular;
     private Date apcDataCadastro;
     private String apcAtivo;

    public ApcClientes() {
    }

	
    public ApcClientes(int apcIdClientes, String apcNome, String apcCpf, String apcRg, String apcSexo, String apcEmail, String apcCep, String apcEndereco, String apcBairro, String apcCidade, String apcCelular, String apcAtivo) {
        this.apcIdClientes = apcIdClientes;
        this.apcNome = apcNome;
        this.apcCpf = apcCpf;
        this.apcRg = apcRg;
        this.apcSexo = apcSexo;
        this.apcEmail = apcEmail;
        this.apcCep = apcCep;
        this.apcEndereco = apcEndereco;
        this.apcBairro = apcBairro;
        this.apcCidade = apcCidade;
        this.apcCelular = apcCelular;
        this.apcAtivo = apcAtivo;
    }
    public ApcClientes(int apcIdClientes, String apcNome, String apcCpf, String apcRg, String apcSexo, Date apcDataNascimento, String apcEmail, String apcCep, String apcEndereco, String apcBairro, String apcCidade, String apcTelefoneResidencial, String apcCelular, Date apcDataCadastro, String apcAtivo, Set apcVendases) {
       this.apcIdClientes = apcIdClientes;
       this.apcNome = apcNome;
       this.apcCpf = apcCpf;
       this.apcRg = apcRg;
       this.apcSexo = apcSexo;
       this.apcDataNascimento = apcDataNascimento;
       this.apcEmail = apcEmail;
       this.apcCep = apcCep;
       this.apcEndereco = apcEndereco;
       this.apcBairro = apcBairro;
       this.apcCidade = apcCidade;
       this.apcTelefoneResidencial = apcTelefoneResidencial;
       this.apcCelular = apcCelular;
       this.apcDataCadastro = apcDataCadastro;
       this.apcAtivo = apcAtivo;
    }
   
     @Id 

    
    @Column(name="apc_idClientes", unique=true, nullable=false)
    public int getApcIdClientes() {
        return this.apcIdClientes;
    }
    
    public void setApcIdClientes(int apcIdClientes) {
        this.apcIdClientes = apcIdClientes;
    }

    
    @Column(name="apc_nome", nullable=false, length=100)
    public String getApcNome() {
        return this.apcNome;
    }
    
    public void setApcNome(String apcNome) {
        this.apcNome = apcNome;
    }

    
    @Column(name="apc_cpf", nullable=false, length=14)
    public String getApcCpf() {
        return this.apcCpf;
    }
    
    public void setApcCpf(String apcCpf) {
        this.apcCpf = apcCpf;
    }

    
    @Column(name="apc_rg", nullable=false, length=10)
    public String getApcRg() {
        return this.apcRg;
    }
    
    public void setApcRg(String apcRg) {
        this.apcRg = apcRg;
    }

    
    @Column(name="apc_sexo", nullable=false, length=1)
    public String getApcSexo() {
        return this.apcSexo;
    }
    
    public void setApcSexo(String apcSexo) {
        this.apcSexo = apcSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apc_dataNascimento", length=10)
    public Date getApcDataNascimento() {
        return this.apcDataNascimento;
    }
    
    public void setApcDataNascimento(Date apcDataNascimento) {
        this.apcDataNascimento = apcDataNascimento;
    }

    
    @Column(name="apc_email", nullable=false, length=80)
    public String getApcEmail() {
        return this.apcEmail;
    }
    
    public void setApcEmail(String apcEmail) {
        this.apcEmail = apcEmail;
    }

    
    @Column(name="apc_cep", nullable=false, length=10)
    public String getApcCep() {
        return this.apcCep;
    }
    
    public void setApcCep(String apcCep) {
        this.apcCep = apcCep;
    }

    
    @Column(name="apc_endereco", nullable=false, length=50)
    public String getApcEndereco() {
        return this.apcEndereco;
    }
    
    public void setApcEndereco(String apcEndereco) {
        this.apcEndereco = apcEndereco;
    }

    
    @Column(name="apc_bairro", nullable=false, length=30)
    public String getApcBairro() {
        return this.apcBairro;
    }
    
    public void setApcBairro(String apcBairro) {
        this.apcBairro = apcBairro;
    }

    
    @Column(name="apc_cidade", nullable=false, length=50)
    public String getApcCidade() {
        return this.apcCidade;
    }
    
    public void setApcCidade(String apcCidade) {
        this.apcCidade = apcCidade;
    }

    
    @Column(name="apc_telefoneResidencial", length=18)
    public String getApcTelefoneResidencial() {
        return this.apcTelefoneResidencial;
    }
    
    public void setApcTelefoneResidencial(String apcTelefoneResidencial) {
        this.apcTelefoneResidencial = apcTelefoneResidencial;
    }

    
    @Column(name="apc_celular", nullable=false, length=18)
    public String getApcCelular() {
        return this.apcCelular;
    }
    
    public void setApcCelular(String apcCelular) {
        this.apcCelular = apcCelular;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apc_dataCadastro", length=10)
    public Date getApcDataCadastro() {
        return this.apcDataCadastro;
    }
    
    public void setApcDataCadastro(Date apcDataCadastro) {
        this.apcDataCadastro = apcDataCadastro;
    }

    
    @Column(name="apc_ativo", nullable=false, length=1)
    public String getApcAtivo() {
        return this.apcAtivo;
    }
    
    public void setApcAtivo(String apcAtivo) {
        this.apcAtivo = apcAtivo;
    }

    @Override
    public String toString() {
        return this.apcNome;
    }



}


