package bean;
// Generated 07/10/2025 13:47:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApcProdutos generated by hbm2java
 */
@Entity
@Table(name="apc_produtos"
    ,catalog="db_arthur_conceicao"
)
public class ApcProdutos  implements java.io.Serializable {


     private int apcIdProdutos;
     private String apcNome;
     private String apcDescricao;
     private double apcPreco;
     private String apcFabricante;
     private int apcCategoria;
     private Date apcDataCadastro;
     private String apcAtivo;

    public ApcProdutos() {
    }

	
    public ApcProdutos(int apcIdProdutos, String apcNome, double apcPreco, String apcFabricante, int apcCategoria, String apcAtivo) {
        this.apcIdProdutos = apcIdProdutos;
        this.apcNome = apcNome;
        this.apcPreco = apcPreco;
        this.apcFabricante = apcFabricante;
        this.apcCategoria = apcCategoria;
        this.apcAtivo = apcAtivo;
    }
    public ApcProdutos(int apcIdProdutos, String apcNome, String apcDescricao, double apcPreco, String apcFabricante, int apcCategoria, Date apcDataCadastro, String apcAtivo, Set apcVendasProdutoses) {
       this.apcIdProdutos = apcIdProdutos;
       this.apcNome = apcNome;
       this.apcDescricao = apcDescricao;
       this.apcPreco = apcPreco;
       this.apcFabricante = apcFabricante;
       this.apcCategoria = apcCategoria;
       this.apcDataCadastro = apcDataCadastro;
       this.apcAtivo = apcAtivo;
    }
   
     @Id 

    
    @Column(name="apc_idProdutos", unique=true, nullable=false)
    public int getApcIdProdutos() {
        return this.apcIdProdutos;
    }
    
    public void setApcIdProdutos(int apcIdProdutos) {
        this.apcIdProdutos = apcIdProdutos;
    }

    
    @Column(name="apc_nome", nullable=false, length=100)
    public String getApcNome() {
        return this.apcNome;
    }
    
    public void setApcNome(String apcNome) {
        this.apcNome = apcNome;
    }

    
    @Column(name="apc_descricao", length=200)
    public String getApcDescricao() {
        return this.apcDescricao;
    }
    
    public void setApcDescricao(String apcDescricao) {
        this.apcDescricao = apcDescricao;
    }

    
    @Column(name="apc_preco", nullable=false, precision=10)
    public double getApcPreco() {
        return this.apcPreco;
    }
    
    public void setApcPreco(double apcPreco) {
        this.apcPreco = apcPreco;
    }

    
    @Column(name="apc_fabricante", nullable=false, length=100)
    public String getApcFabricante() {
        return this.apcFabricante;
    }
    
    public void setApcFabricante(String apcFabricante) {
        this.apcFabricante = apcFabricante;
    }

    
    @Column(name="apc_categoria", nullable=false, length=50)
    public int getApcCategoria() {
        return this.apcCategoria;
    }
    
    public void setApcCategoria(int apcCategoria) {
        this.apcCategoria = apcCategoria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apc_dataCadastro", length=10)
    public Date getApcDataCadastro() {
        return this.apcDataCadastro;
    }
    
    public void setApcDataCadastro(Date apcDataCadastro) {
        this.apcDataCadastro = apcDataCadastro;
    }

    
    @Column(name="apc_ativo", nullable=false, length=1)
    public String getApcAtivo() {
        return this.apcAtivo;
    }
    
    public void setApcAtivo(String apcAtivo) {
        this.apcAtivo = apcAtivo;
    }



}


