package bean;
// Generated 07/10/2025 13:47:15 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApcUsuarios generated by hbm2java
 */
@Entity
@Table(name="apc_usuarios"
    ,catalog="db_arthur_conceicao"
)
public class ApcUsuarios  implements java.io.Serializable {


     private int apcIdUsuarios;
     private String apcNome;
     private String apcApelido;
     private String apcCpf;
     private Date apcDataNascimento;
     private String apcSenha;
     private int apcNivel;
     private String apcAtivo;

    public ApcUsuarios() {
    }

	
    public ApcUsuarios(int apcIdUsuarios, String apcNome, String apcApelido, String apcCpf, String apcSenha, int apcNivel, String apcAtivo) {
        this.apcIdUsuarios = apcIdUsuarios;
        this.apcNome = apcNome;
        this.apcApelido = apcApelido;
        this.apcCpf = apcCpf;
        this.apcSenha = apcSenha;
        this.apcNivel = apcNivel;
        this.apcAtivo = apcAtivo;
    }
    public ApcUsuarios(int apcIdUsuarios, String apcNome, String apcApelido, String apcCpf, Date apcDataNascimento, String apcSenha, int apcNivel, String apcAtivo) {
       this.apcIdUsuarios = apcIdUsuarios;
       this.apcNome = apcNome;
       this.apcApelido = apcApelido;
       this.apcCpf = apcCpf;
       this.apcDataNascimento = apcDataNascimento;
       this.apcSenha = apcSenha;
       this.apcNivel = apcNivel;
       this.apcAtivo = apcAtivo;
    }
   
     @Id 

    
    @Column(name="apc_idUsuarios", unique=true, nullable=false)
    public int getApcIdUsuarios() {
        return this.apcIdUsuarios;
    }
    
    public void setApcIdUsuarios(int apcIdUsuarios) {
        this.apcIdUsuarios = apcIdUsuarios;
    }

    
    @Column(name="apc_nome", nullable=false, length=50)
    public String getApcNome() {
        return this.apcNome;
    }
    
    public void setApcNome(String apcNome) {
        this.apcNome = apcNome;
    }

    
    @Column(name="apc_apelido", nullable=false, length=25)
    public String getApcApelido() {
        return this.apcApelido;
    }
    
    public void setApcApelido(String apcApelido) {
        this.apcApelido = apcApelido;
    }

    
    @Column(name="apc_cpf", nullable=false, length=14)
    public String getApcCpf() {
        return this.apcCpf;
    }
    
    public void setApcCpf(String apcCpf) {
        this.apcCpf = apcCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apc_dataNascimento", length=10)
    public Date getApcDataNascimento() {
        return this.apcDataNascimento;
    }
    
    public void setApcDataNascimento(Date apcDataNascimento) {
        this.apcDataNascimento = apcDataNascimento;
    }

    
    @Column(name="apc_senha", nullable=false, length=20)
    public String getApcSenha() {
        return this.apcSenha;
    }
    
    public void setApcSenha(String apcSenha) {
        this.apcSenha = apcSenha;
    }

    
    @Column(name="apc_nivel", nullable=false, length=15)
    public int getApcNivel() {
        return this.apcNivel;
    }
    
    public void setApcNivel(int apcNivel) {
        this.apcNivel = apcNivel;
    }

    
    @Column(name="apc_ativo", nullable=false, length=1)
    public String getApcAtivo() {
        return this.apcAtivo;
    }
    
    public void setApcAtivo(String apcAtivo) {
        this.apcAtivo = apcAtivo;
    }




}


