package bean;
// Generated 07/10/2025 13:47:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApcVendas generated by hbm2java
 */
@Entity
@Table(name="apc_vendas"
    ,catalog="db_arthur_conceicao"
)
public class ApcVendas  implements java.io.Serializable {


     private int apcIdPedidos;
     private ApcClientes apcClientes;
     private ApcVendedor apcVendedor;
     private Date apcDataPedido;
     private String apcStatus;
     private double apcTotal;
     private String apcFormaPagamento;
     private String apcObservacao;

    public ApcVendas() {
    }

	
    public ApcVendas(int apcIdPedidos, ApcClientes apcClientes, ApcVendedor apcVendedor, double apcTotal) {
        this.apcIdPedidos = apcIdPedidos;
        this.apcClientes = apcClientes;
        this.apcVendedor = apcVendedor;
        this.apcTotal = apcTotal;
    }
    public ApcVendas(int apcIdPedidos, ApcClientes apcClientes, ApcVendedor apcVendedor, Date apcDataPedido, String apcStatus, double apcTotal, String apcFormaPagamento, String apcObservacao, Set apcVendasProdutoses) {
       this.apcIdPedidos = apcIdPedidos;
       this.apcClientes = apcClientes;
       this.apcVendedor = apcVendedor;
       this.apcDataPedido = apcDataPedido;
       this.apcStatus = apcStatus;
       this.apcTotal = apcTotal;
       this.apcFormaPagamento = apcFormaPagamento;
       this.apcObservacao = apcObservacao;
    }
   
     @Id 

    
    @Column(name="apc_idPedidos", unique=true, nullable=false)
    public int getApcIdPedidos() {
        return this.apcIdPedidos;
    }
    
    public void setApcIdPedidos(int apcIdPedidos) {
        this.apcIdPedidos = apcIdPedidos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="apc_idClientes", nullable=false)
    public ApcClientes getApcClientes() {
        return this.apcClientes;
    }
    
    public void setApcClientes(ApcClientes apcClientes) {
        this.apcClientes = apcClientes;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="apc_idVendedor", nullable=false)
    public ApcVendedor getApcVendedor() {
        return this.apcVendedor;
    }
    
    public void setApcVendedor(ApcVendedor apcVendedor) {
        this.apcVendedor = apcVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apc_dataPedido", length=10)
    public Date getApcDataPedido() {
        return this.apcDataPedido;
    }
    
    public void setApcDataPedido(Date apcDataPedido) {
        this.apcDataPedido = apcDataPedido;
    }

    
    @Column(name="apc_status", length=10)
    public String getApcStatus() {
        return this.apcStatus;
    }
    
    public void setApcStatus(String apcStatus) {
        this.apcStatus = apcStatus;
    }

    
    @Column(name="apc_total", nullable=false, precision=10)
    public double getApcTotal() {
        return this.apcTotal;
    }
    
    public void setApcTotal(double apcTotal) {
        this.apcTotal = apcTotal;
    }

    
    @Column(name="apc_formaPagamento", length=20)
    public String getApcFormaPagamento() {
        return this.apcFormaPagamento;
    }
    
    public void setApcFormaPagamento(String apcFormaPagamento) {
        this.apcFormaPagamento = apcFormaPagamento;
    }

    
    @Column(name="apc_observacao", length=200)
    public String getApcObservacao() {
        return this.apcObservacao;
    }
    
    public void setApcObservacao(String apcObservacao) {
        this.apcObservacao = apcObservacao;
    }

}


