package bean;
// Generated 07/10/2025 13:47:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApcVendedor generated by hbm2java
 */
@Entity
@Table(name="apc_vendedor"
    ,catalog="db_arthur_conceicao"
)
public class ApcVendedor  implements java.io.Serializable {


     private int apcIdVendedor;
     private String apcNome;
     private String apcCpf;
     private Date apcDataNascimento;
     private String apcSexo;
     private String apcCep;
     private String apcEndereco;
     private String apcBairro;
     private String apcCidade;
     private String apcCelular;
     private String apcTelefoneResidencial;
     private String apcCargo;
     private double apcSalario;
     private Date apcDataAdimissao;
     private String apcAtivo;

    public ApcVendedor() {
    }

	
    public ApcVendedor(int apcIdVendedor, String apcNome, String apcCpf, String apcSexo, String apcCep, String apcEndereco, String apcBairro, String apcCidade, String apcCelular, String apcCargo, double apcSalario, String apcAtivo) {
        this.apcIdVendedor = apcIdVendedor;
        this.apcNome = apcNome;
        this.apcCpf = apcCpf;
        this.apcSexo = apcSexo;
        this.apcCep = apcCep;
        this.apcEndereco = apcEndereco;
        this.apcBairro = apcBairro;
        this.apcCidade = apcCidade;
        this.apcCelular = apcCelular;
        this.apcCargo = apcCargo;
        this.apcSalario = apcSalario;
        this.apcAtivo = apcAtivo;
    }
    public ApcVendedor(int apcIdVendedor, String apcNome, String apcCpf, Date apcDataNascimento, String apcSexo, String apcCep, String apcEndereco, String apcBairro, String apcCidade, String apcCelular, String apcTelefoneResidencial, String apcCargo, double apcSalario, Date apcDataAdimissao, String apcAtivo, Set apcVendases) {
       this.apcIdVendedor = apcIdVendedor;
       this.apcNome = apcNome;
       this.apcCpf = apcCpf;
       this.apcDataNascimento = apcDataNascimento;
       this.apcSexo = apcSexo;
       this.apcCep = apcCep;
       this.apcEndereco = apcEndereco;
       this.apcBairro = apcBairro;
       this.apcCidade = apcCidade;
       this.apcCelular = apcCelular;
       this.apcTelefoneResidencial = apcTelefoneResidencial;
       this.apcCargo = apcCargo;
       this.apcSalario = apcSalario;
       this.apcDataAdimissao = apcDataAdimissao;
       this.apcAtivo = apcAtivo;
    }
   
     @Id 

    
    @Column(name="apc_idVendedor", unique=true, nullable=false)
    public int getApcIdVendedor() {
        return this.apcIdVendedor;
    }
    
    public void setApcIdVendedor(int apcIdVendedor) {
        this.apcIdVendedor = apcIdVendedor;
    }

    
    @Column(name="apc_nome", nullable=false, length=50)
    public String getApcNome() {
        return this.apcNome;
    }
    
    public void setApcNome(String apcNome) {
        this.apcNome = apcNome;
    }

    
    @Column(name="apc_cpf", nullable=false, length=14)
    public String getApcCpf() {
        return this.apcCpf;
    }
    
    public void setApcCpf(String apcCpf) {
        this.apcCpf = apcCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apc_dataNascimento", length=10)
    public Date getApcDataNascimento() {
        return this.apcDataNascimento;
    }
    
    public void setApcDataNascimento(Date apcDataNascimento) {
        this.apcDataNascimento = apcDataNascimento;
    }

    
    @Column(name="apc_sexo", nullable=false, length=1)
    public String getApcSexo() {
        return this.apcSexo;
    }
    
    public void setApcSexo(String apcSexo) {
        this.apcSexo = apcSexo;
    }

    
    @Column(name="apc_cep", nullable=false, length=10)
    public String getApcCep() {
        return this.apcCep;
    }
    
    public void setApcCep(String apcCep) {
        this.apcCep = apcCep;
    }

    
    @Column(name="apc_endereco", nullable=false, length=50)
    public String getApcEndereco() {
        return this.apcEndereco;
    }
    
    public void setApcEndereco(String apcEndereco) {
        this.apcEndereco = apcEndereco;
    }

    
    @Column(name="apc_bairro", nullable=false, length=30)
    public String getApcBairro() {
        return this.apcBairro;
    }
    
    public void setApcBairro(String apcBairro) {
        this.apcBairro = apcBairro;
    }

    
    @Column(name="apc_cidade", nullable=false, length=50)
    public String getApcCidade() {
        return this.apcCidade;
    }
    
    public void setApcCidade(String apcCidade) {
        this.apcCidade = apcCidade;
    }

    
    @Column(name="apc_celular", nullable=false, length=18)
    public String getApcCelular() {
        return this.apcCelular;
    }
    
    public void setApcCelular(String apcCelular) {
        this.apcCelular = apcCelular;
    }

    
    @Column(name="apc_telefoneResidencial", length=18)
    public String getApcTelefoneResidencial() {
        return this.apcTelefoneResidencial;
    }
    
    public void setApcTelefoneResidencial(String apcTelefoneResidencial) {
        this.apcTelefoneResidencial = apcTelefoneResidencial;
    }

    
    @Column(name="apc_cargo", nullable=false, length=30)
    public String getApcCargo() {
        return this.apcCargo;
    }
    
    public void setApcCargo(String apcCargo) {
        this.apcCargo = apcCargo;
    }

    
    @Column(name="apc_salario", nullable=false, precision=10)
    public double getApcSalario() {
        return this.apcSalario;
    }
    
    public void setApcSalario(double apcSalario) {
        this.apcSalario = apcSalario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apc_dataAdimissao", length=10)
    public Date getApcDataAdimissao() {
        return this.apcDataAdimissao;
    }
    
    public void setApcDataAdimissao(Date apcDataAdimissao) {
        this.apcDataAdimissao = apcDataAdimissao;
    }

    
    @Column(name="apc_ativo", nullable=false, length=1)
    public String getApcAtivo() {
        return this.apcAtivo;
    }
    
    public void setApcAtivo(String apcAtivo) {
        this.apcAtivo = apcAtivo;
    }

}


