package bean;
// Generated 07/10/2025 13:47:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApcVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="apc_vendas_produtos"
    ,catalog="db_arthur_conceicao"
)
public class ApcVendasProdutos  implements java.io.Serializable {


     private int apcIdItem;
     private ApcProdutos apcProdutos;
     private ApcVendas apcVendas;
     private int apcQuantidade;
     private double apcPrecoUnitario;
     private double apcSubtotal;
     private double apcDesconto;

    public ApcVendasProdutos() {
    }

	
    public ApcVendasProdutos(int apcIdItem, ApcProdutos apcProdutos, ApcVendas apcVendas, int apcQuantidade, double apcPrecoUnitario, double apcSubtotal) {
        this.apcIdItem = apcIdItem;
        this.apcProdutos = apcProdutos;
        this.apcVendas = apcVendas;
        this.apcQuantidade = apcQuantidade;
        this.apcPrecoUnitario = apcPrecoUnitario;
        this.apcSubtotal = apcSubtotal;
    }
    public ApcVendasProdutos(int apcIdItem, ApcProdutos apcProdutos, ApcVendas apcVendas, int apcQuantidade, double apcPrecoUnitario, double apcSubtotal, double apcDesconto) {
       this.apcIdItem = apcIdItem;
       this.apcProdutos = apcProdutos;
       this.apcVendas = apcVendas;
       this.apcQuantidade = apcQuantidade;
       this.apcPrecoUnitario = apcPrecoUnitario;
       this.apcSubtotal = apcSubtotal;
       this.apcDesconto = apcDesconto;
    }
   
     @Id 

    
    @Column(name="apc_idItem", unique=true, nullable=false)
    public int getApcIdItem() {
        return this.apcIdItem;
    }
    
    public void setApcIdItem(int apcIdItem) {
        this.apcIdItem = apcIdItem;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="apc_idProdutos", nullable=false)
    public ApcProdutos getApcProdutos() {
        return this.apcProdutos;
    }
    
    public void setApcProdutos(ApcProdutos apcProdutos) {
        this.apcProdutos = apcProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="apc_idPedidos", nullable=false)
    public ApcVendas getApcVendas() {
        return this.apcVendas;
    }
    
    public void setApcVendas(ApcVendas apcVendas) {
        this.apcVendas = apcVendas;
    }

    
    @Column(name="apc_quantidade", nullable=false)
    public int getApcQuantidade() {
        return this.apcQuantidade;
    }
    
    public void setApcQuantidade(int apcQuantidade) {
        this.apcQuantidade = apcQuantidade;
    }

    
    @Column(name="apc_precoUnitario", nullable=false, precision=10)
    public double getApcPrecoUnitario() {
        return this.apcPrecoUnitario;
    }
    
    public void setApcPrecoUnitario(double apcPrecoUnitario) {
        this.apcPrecoUnitario = apcPrecoUnitario;
    }

    
    @Column(name="apc_subtotal", nullable=false, precision=10)
    public double getApcSubtotal() {
        return this.apcSubtotal;
    }
    
    public void setApcSubtotal(double apcSubtotal) {
        this.apcSubtotal = apcSubtotal;
    }

    
    @Column(name="apc_desconto", precision=10)
    public double getApcDesconto() {
        return this.apcDesconto;
    }
    
    public void setApcDesconto(double apcDesconto) {
        this.apcDesconto = apcDesconto;
    }




}


